# Generated by Django 4.1.3 on 2022-11-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="view_count",),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="total",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
