# Generated by Django 4.1.3 on 2022-11-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_remove_product_view_count_order_subtotal_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="price", new_name="selling_price",
        ),
    ]
