# Generated by Django 4.1.3 on 2022-11-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0003_rename_price_product_selling_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="quantity",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
