# Generated by Django 4.1.3 on 2022-11-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0005_alter_cartproduct_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="quantity",
            field=models.PositiveIntegerField(default="test"),
        ),
    ]
