# Generated by Django 4.1.3 on 2022-11-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0006_alter_cartproduct_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
