# Generated by Django 4.1.7 on 2023-02-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0010_video"),
    ]

    operations = [
        migrations.DeleteModel(name="Video",),
    ]
