# Generated by Django 4.1.7 on 2023-02-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0012_paymentselections"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_completed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("Cash On Delivery", "Cash On Dlivery"), ("Khatli", "Khatli")],
                default="Cash On Delivery",
                max_length=20,
            ),
        ),
    ]
