# Generated by Django 4.1.7 on 2023-03-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0013_order_payment_completed_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash On Delivery", "Cash On Dlivery"),
                    ("Khalti", "Khalti"),
                    ("PayPal", "PayPal"),
                ],
                default="Cash On Delivery",
                max_length=20,
            ),
        ),
    ]
